version: "3.1"
services:
  seata-server:
    image: seataio/seata-server:1.5.1
    hostname: seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file