version: '3.8'
services:
  redis:
    image: 'redis:latest'
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  master-mongo:
    image: mongo
    container_name: master-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/master:/data/db
    command: mongod --dbpath /data/db --replSet testSet --oplogSize 128
  secondary-mongo:
    image: mongo
    container_name: secondary-mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data/secondary:/data/db
    command: mongod --dbpath /data/db --replSet testSet --oplogSize 128
  arbiter-mongo:
    image: mongo
    container_name: arbiter-mongo
    ports:
      - "27019:27017"
    volumes:
      - ./data/arbiter:/data/db
    command: mongod --dbpath /data/db --replSet testSet --oplogSize 128
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root111
  nacos:
    image: 'nacos/nacos-server:latest'
    container_name: nacos
    restart: always
    ports:
      - 8848:8848
    links:
      - mysql
    environment:
      - MODE=standalone
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
  rabbitmq:
    image: 'rabbitmq:3.8.3-management'
    container_name: rabbitmq
    restart: always
    ports:
      - 5671:5671
      - 5672:5672
      - 4369:4369
      - 25672:25672
      - 15671:15671
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin