version: '3.1'
services:
#  mysql8:
#    image: mysql:8.0.28
#    command: --default-authentication-plugin=mysql_native_password
#    platform: linux/amd64
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root111
#    ports:
#      - 3306:3306
  mysql5:
    image: mysql:5.7.38
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root111
    ports:
      - 3306:3306
#  adminer:
#    image: adminer:standalone
#    platform: linux/amd64
#    restart: always
#    ports:
#      - 9090:8080
#    links:
#      - db