version: '3.1'
services:
  db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root111
    ports:
      - 3306:3306
#  adminer:
#    image: adminer:standalone
#    platform: linux/amd64
#    restart: always
#    ports:
#      - 9090:8080
#    links:
#      - db